### ISSUE TITLE
GCTNET code link cannot be found

### ISSUE THREAD

**Issue by fencesitter1** [UGeunJi/AI_Papers-and-Mathematics#1]
Have you reproduced this GCTNet article?It is awesome. You recorded the entire reproduction process, which is worth learning from. But it seems that the code link is not accessible. I wonder if you can share the code?

**Comment by UGeunJi** [comment]
Thank you for your interest. If you just want a link to an existing code, you can refer to this link (https://github.com/JinY97/GCTNet).
However, if you want the code I developed, I regret that I can't provide it because it's an ongoing study.

**Comment by fencesitter1** [comment]
Thanks for your reply. I understand your refusal and wish you success in your scientific research.
